name: selenium-github-actions
on:
  schedule:
    - cron: '0 4 * * *'
jobs:
  selenium:
    runs-on: ubuntu-latest
    steps:
      - uses: browser-actions/setup-chrome@latest
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - run: |
          chrome --version
          pip install -r ./requirements.txt
          python ./main.py ${{secrets.LINE_API_KEY}}
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "create or update data_file!" || echo "No changes to commit"
          git push
